openapi: 3.0.3
info:
  title: School API
  version: 0.1.0
  license:
    name: Proprietary
    url: https://donasky.com/license
servers:
  - url: https://donasky.com
  - url: http://localhost:8080

tags:
  - name: Classes
    description: Class management APIs

paths:
  /classes:
    $ref: ./paths/classes.yaml#/classes
  /classes/{classId}:
    $ref: ./paths/classes.yaml#/classById

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
